"""Prespecified study contracts."""

from abmforge_finance.study.precision import (
    PrecisionCheckpointArtifact,
    PrecisionContrastWidth,
    PrecisionMetricArtifact,
    PrecisionPilotArtifact,
    build_precision_pilot_artifact,
    run_flagship_precision_pilot,
    verify_bundled_flagship_protocol,
    verify_precision_pilot_artifact,
    verify_precision_pilot_experiments,
    write_precision_pilot_artifact,
)
from abmforge_finance.study.protocol import (
    FlagshipStudyProtocol,
    MultiplicityMethod,
    OutcomeRole,
    PrecisionPilotPlan,
    PrecisionPilotReport,
    PrecisionTarget,
    RobustnessRegime,
    StudyOutcome,
    apply_robustness_regime,
    bundled_flagship_protocol_mapping,
    confirmatory_seed_tuple,
    evaluate_precision_pilot,
    flagship_narrative_stability_protocol,
    precision_pilot_seed_tuple,
    study_seed_tuple,
)

__all__ = [
    "FlagshipStudyProtocol",
    "MultiplicityMethod",
    "OutcomeRole",
    "PrecisionCheckpointArtifact",
    "PrecisionContrastWidth",
    "PrecisionMetricArtifact",
    "PrecisionPilotArtifact",
    "PrecisionPilotPlan",
    "PrecisionPilotReport",
    "PrecisionTarget",
    "RobustnessRegime",
    "StudyOutcome",
    "apply_robustness_regime",
    "build_precision_pilot_artifact",
    "bundled_flagship_protocol_mapping",
    "confirmatory_seed_tuple",
    "evaluate_precision_pilot",
    "flagship_narrative_stability_protocol",
    "precision_pilot_seed_tuple",
    "run_flagship_precision_pilot",
    "study_seed_tuple",
    "verify_bundled_flagship_protocol",
    "verify_precision_pilot_artifact",
    "verify_precision_pilot_experiments",
    "write_precision_pilot_artifact",
]
