"""Public package interface for :mod:`abmforge_finance`."""

from importlib.metadata import PackageNotFoundError, version

from abmforge_finance.domain import (
    Account,
    Instrument,
    Order,
    OrderType,
    Portfolio,
    Side,
    TimeInForce,
    Trade,
)
from abmforge_finance.exceptions import (
    ClearingError,
    CrossingOrderError,
    DomainValidationError,
    DuplicateOrderError,
    DuplicateParticipantError,
    DuplicateSequenceNumberError,
    DuplicateSettlementError,
    ExchangeError,
    ExchangeInvariantError,
    FinanceError,
    InsufficientAvailableInventoryError,
    InsufficientBuyingPowerError,
    InsufficientCashError,
    InsufficientInventoryError,
    InvalidAccountError,
    InvalidBookOrderError,
    InvalidClearingRegistrationError,
    InvalidDepthError,
    InvalidIncomingOrderError,
    InvalidInstrumentError,
    InvalidOrderError,
    InvalidPortfolioError,
    InvalidPriceError,
    InvalidQuantityError,
    InvalidTradeError,
    MarketError,
    MatchingEngineError,
    OrderBookError,
    OrderBookInvariantError,
    OrderNotFoundError,
    OrderOwnershipError,
    OutOfOrderSettlementError,
    OverfillError,
    SettlementInvariantError,
    UnknownParticipantError,
)
from abmforge_finance.market import (
    ClearingEngine,
    DepthLevel,
    Exchange,
    ExchangeResult,
    LimitOrderBook,
    MatchingEngine,
    MatchResult,
    OrderBookSnapshot,
    SettlementResult,
)

try:
    __version__ = version("abmforge-finance")
except PackageNotFoundError:  # pragma: no cover - only for an unpackaged source tree
    __version__ = "0.1.0a0"

__all__ = [
    "Account",
    "ClearingEngine",
    "ClearingError",
    "CrossingOrderError",
    "DepthLevel",
    "DomainValidationError",
    "DuplicateOrderError",
    "DuplicateParticipantError",
    "DuplicateSequenceNumberError",
    "DuplicateSettlementError",
    "Exchange",
    "ExchangeError",
    "ExchangeInvariantError",
    "ExchangeResult",
    "FinanceError",
    "Instrument",
    "InsufficientAvailableInventoryError",
    "InsufficientBuyingPowerError",
    "InsufficientCashError",
    "InsufficientInventoryError",
    "InvalidAccountError",
    "InvalidBookOrderError",
    "InvalidClearingRegistrationError",
    "InvalidDepthError",
    "InvalidIncomingOrderError",
    "InvalidInstrumentError",
    "InvalidOrderError",
    "InvalidPortfolioError",
    "InvalidPriceError",
    "InvalidQuantityError",
    "InvalidTradeError",
    "LimitOrderBook",
    "MarketError",
    "MatchResult",
    "MatchingEngine",
    "MatchingEngineError",
    "Order",
    "OrderBookError",
    "OrderBookInvariantError",
    "OrderBookSnapshot",
    "OrderNotFoundError",
    "OrderOwnershipError",
    "OrderType",
    "OutOfOrderSettlementError",
    "OverfillError",
    "Portfolio",
    "SettlementInvariantError",
    "SettlementResult",
    "Side",
    "TimeInForce",
    "Trade",
    "UnknownParticipantError",
    "__version__",
]
